### ISSUE TITLE
Disable automatic restart/reboot after Windows 11 Update

### ISSUE THREAD

**Issue by ghnp5** [LeDragoX/Win-10-Smart-Debloat-Tools#30]
### Description

Is there a way to stop Windows 11 from automatically restarting after installing Updates, using this tool?
If not, do you know any tool that supports doing it?

I don't want disable Updates. I just want to restart Windows whenever I ready, and not while I'm away from the PC.

I used to be able to do this by replacing the `Reboot` file with a folder inside `C:\Windows\System32\Tasks\Microsoft\Windows\UpdateOrchestrator`, but they keep changing these things, so it's not possible anymore.

Thank you!

### Reason

N/A

### Examples

N/A

**Comment by LeDragoX** [comment]
Okay, if you're using Windows 11 Pro, you can change the policies to stop automatic updates, i did this on the script tweaks, making the user being notified when there's a new update, and letting him to choose when to **Download and Install** (Manually).

The script configure the policies via registry, so most from there can be undone.

If you're on Windows 11 Home, i don't know if there's a way to do this, but maybe setting the **active hours** to install to a hour the PC is shutdown or no one's using it.

As i'm current on Windows 10 Pro, i didn't expected a new registry key being set to do automatic restarts.
> I'll do some research

**Comment by LeDragoX** [comment]
If this didn't solved the problem, you can Reopen this issue @ghnp5

**Comment by ghnp5** [comment]
Alright, at least this policy does exist. I wasn't aware of it:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/57591332/171393506-e5d5f83d-946d-4e5c-9d23-01e8f78042fd.png">

And it did create that NoAutoRebootWithLoggedOnUsers you found:

<img width="253" alt="image" src="https://user-images.githubusercontent.com/57591332/171393665-a90b8656-3d7b-461c-b497-dd1e12704ff4.png">

So this should at least validate that it's correct and should work! :)

**Comment by ghnp5** [comment]
@LeDragoX  - btw, even though this policy is enabled, Windows 11 is still going ahead and restart whenever it decides :-(

**Comment by LeDragoX** [comment]
> @LeDragoX - btw, even though this policy is enabled, Windows 11 is still going ahead and restart whenever it decides :-(

Well then, i don't know any other solution on how to solve this. Thanks Microsoft...
