### ISSUE TITLE
It's possible keep disabled Windows Search service?

### ISSUE THREAD

**Issue by peter9811** [LeDragoX/Win-10-Smart-Debloat-Tools#36]
### Description

Always that I apply the tool, the Windows Search service run again, using a lot of CPU and I really don't use this function 

Thanks 

### Reason

Windows Search service run again

### Examples

N/A

**Comment by LeDragoX** [comment]
Yes, it's on the GUI, and it's enabled because u're using a SSD.
You can disable through here
![image](https://user-images.githubusercontent.com/27643047/173195171-46f8b281-fa5f-455a-9fed-4aaa92164f0e.png)
Right here on "Enable Search Indexing", clicking twice will disable again.

**Comment by LeDragoX** [comment]
After this i should rename the function to a better name.
