### ISSUE TITLE
Edge `managed by Organization`

### ISSUE THREAD

**Issue by b1r0c** [LeDragoX/Win-10-Smart-Debloat-Tools#8]
## Bug Report

After applying tweaks, edge reports that's managed by organization and all the policies are set to false. 

### Environment?

- System Specs:
  - OS:  Windows 11
  
- Date Executed: 20-10-21

**Comment by kieusonlam** [comment]
Hi, sorry for bordering. I want to revert config for Edge, what should I do?

**Comment by LeDragoX** [comment]
@kieusonlam sorry for the delay, but you can do it by using a separate application, called ShutUp10 (which is in the script, but is also deleted after used), or reverting all the tweaks, I didn't made any checkbox for it atm.
